In [161]:
import numpy as np

In [162]:
a = np.array([[1, 2], [2, 3], [3, 4]])
a

array([[1, 2],
       [2, 3],
       [3, 4]])

In [163]:
b = np.arange(1, 11, 2) # заполнение массива начиная с 1, заканчивая 11 (не включительно) с шагом 2
b

array([1, 3, 5, 7, 9])

In [164]:
c = np.zeros([2, 5]) # заполнение массива размерностью 2х5 нулями
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [165]:
d = np.ones([2, 5]) # заполнение массива размерностью 2х5 единицами
d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [166]:
res = c + 2*d # поэлементрое сложение двух матриц
res

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [167]:
res.shape

(2, 5)

In [168]:
res.dtype

dtype('float64')

In [169]:
import numpy.random as rand

In [170]:
np.random.seed(50)
a = np.random.randint(10, 30, (3, 5))
a

array([[26, 10, 21, 23, 11],
       [14, 16, 15, 16, 23],
       [15, 12, 17, 25, 14]], dtype=int32)

In [171]:
a[2][3] # выводит элемент под индексом 3 строки с индексом 2

np.int32(25)

In [172]:
a[2] # выводит все элементы строки с индексом 2

array([15, 12, 17, 25, 14], dtype=int32)

In [173]:
a[:, 3:] # выводит элементы всех строк, начиная с индекса 4 

array([[23, 11],
       [16, 23],
       [25, 14]], dtype=int32)

In [174]:
np.random.seed(50)
a = np.random.randint(10, 20, (3, 4))
b = np.random.randint(30, 40, (2, 6))
a, b

(array([[10, 10, 11, 14],
        [16, 15, 16, 16],
        [15, 12, 17, 14]], dtype=int32),
 array([[33, 36, 34, 31, 35, 39],
        [30, 36, 33, 32, 39, 33]], dtype=int32))

In [175]:
b.shape = (3, 4)  # перед тем как поэлементно складывать или умножать массивы, нужно их привести к одной размерности 

In [176]:
a + b

array([[43, 46, 45, 45],
       [51, 54, 46, 52],
       [48, 44, 56, 47]], dtype=int32)

In [177]:
a*b

array([[330, 360, 374, 434],
       [560, 585, 480, 576],
       [495, 384, 663, 462]], dtype=int32)

In [178]:
b.shape = (4, 3) # при матричном умножении "внутренние" размерности должны совпадать
b

array([[33, 36, 34],
       [31, 35, 39],
       [30, 36, 33],
       [32, 39, 33]], dtype=int32)

In [179]:
res = a @ b # получили массив с размерностью 3 на 3
res

array([[1418, 1652, 1555],
       [1985, 2301, 2185],
       [1825, 2118, 2001]], dtype=int32)

In [180]:
res.mean() # среднее арифмитическое всех элементов

np.float64(1893.3333333333333)

In [181]:
res.max() # максимальный из всех элементов массива

np.int32(2301)

In [182]:
res[2].mean() # среднее арифмитическое элементов строки с индексом 2

np.float64(1981.3333333333333)

In [183]:
res[:, 2].mean() # среднее арифмитическое элементов столбца с индексом 2

np.float64(1913.6666666666667)