# Математика в Python
Приветствую! Мы начинаем изучение замечательной области машинного обучения, которая позволяет обучать компьютеры решать многие задачи образом, похожим на то, как обучается человек.
В курсе мы будем пользоваться многими библиотеками замечательного языка Python, с которым вы немного знакомы. И прежде чем начинать изучать машинное обучение мы познакомимся со способами работы и отображения данных.   

Сегодня мы посмотрим, как можно выполнять математические операции в Python, посмотрим на разные типы *объектов* и переменных.

Объект - это то, что действительно хранится в определенном месте памяти компьютера. Конечно, там хранятся только последовательности из 0 и 1, но мы можем по-разному *представлять* себе к чему такие последовательности относятся. В нашем представлении это могут быть числа, это могут быть строки, изображения, и все что угодно. Важно правильно хранить и правильно обращаться (или как говорят *читать*) к этим данным. Чтобы человеку-программисту было понятно с каким объектом он работает, объект имеет название или, по-другому, *имя*.

По своей сути *имя* объекта для человека это название, но для компьютера это *адрес* (ссылка, номер) ячейки памяти, где хранится объект. Если объект хранится в нескольких ячейках, то имя это  адрес первой ячейки.

Надо различать имя переменной и ее содержимое, т.е. тот объект, на который она ссылается. Обычно одному объекту соответствует одно имя, но может быть и по-другому. Один и тот же объект может иметь два и больше имен, это бывает удобно для программиста, если надо, а не хочется переименовать свой объект.

Один из типов данных, и самый важный, это *числа*.

Одно число называют *скаляр* и с ним можно выполнять разные математические операции.

Набор (говорят *массив* или *тензор*) из нескольких чисел можно представить по-разному, в одномерном, двумерном, трехмерном варианте или даже больше.

![img](https://drive.google.com/uc?id=13UY_qQy4w_GhJS-VXOHHg2yPFaml72Lt)

Одномерный массив называется *вектор* (или строка), двумерный - *матрица*. Многомерный называют просто массивом указывая его размерность. Часто трехмерный массив называют *тензор*, хотя это неправильно, тензор может быть любой размерности.

В массивах (а мы помним, что массив это набор чисел) важно не только количество элементов, но и как именно они расположены, массивы имеют *форму*. 30 чисел можно по-разному расположить:

  * друг за другом в одной строке - получим одномерный массив - строку.
  * друг под другом в одном столбце -  получим тоже одномерный массив, но уже вектор.
  * 6 строк, в каждой по 5 элементов - получили матрицу размером 6 * 5
  * 5 строк, в каждой по 6 элементов - получили матрицу размером 5 * 6
  * 3 строки по 5 элементов - получим матрицу 3 * 5 и сделаем еще одну матрицу 3 * 5 - получили две матрицы одинакового размера, можем их поставить друг за другом и представить как параллелепипед - получили трехмерный массив.
  
  И так далее, придумайте свои варианты размещения элементов и определите форму (размерность и размеры) массива.
  



# 1. Математические операции со скалярами.
Со скалярами можно выполнять разные математические операции. Многие библиотеки (модули) имеют уже готовые решения для этого, базовые операции встроены в сам Python.

In [8]:
a = 5   # зададим число a
b = 0.3   # зададим число b

In [9]:
a

5

In [10]:
c=a+7 # сложение чисел

In [11]:
c

12

In [12]:
a-b # вычитание чисел

4.7

In [13]:
a*b # умножение чисел

1.5

In [14]:
a/b # деление чисел

16.666666666666668

In [15]:
# Раскомментируйте две строчки ниже и попробуйте поделить на ноль.
b=0 # а если поделим на 0?
a/b # возникнет ошибка, на 0 делить нельзя.

ZeroDivisionError: division by zero

# 2. Модуль `math`
Для более сложных операций рассмотрим модуль [`math`](https://pythonworld.ru/moduli/modul-math.html).

Сначала его нужно подключить с помощью команды `import`.

In [17]:
import math

In [ ]:
#math

## Округление
Попробуйте округлять разные числа *a* и ответьте, чем отличаются эти два способа `ceil` и `floor`.

In [18]:
# Округление
a=3.2
b=math.ceil(a) # округление к ближайшему большему целому.
c=math.floor(a) #округление вниз
b, c

(4, 3)

## Модуль числа
Попробуйте для положительных и отрицательных чисел.

In [19]:
a=-7
d=math.fabs(a)
d

7.0

In [20]:
print(a,d)

-7 7.0


## Остаток от деления $c=mod_b(a)$
Попробуйте для разных целых чисел __a__ и __b__ и скажите, что же это за функция `fmod`.

Могут ли __a__ и __b__ быть отрицательными?

Может ли __a=0__? Может ли __b=0__? Может ли __b=1__, какой будет результат в этом случае?

> В отличии от того, чему нас учат в школе, в этой функции __a__ и __b__ могут быть дробными. Но мы таким пользоваться не будем.

In [21]:
a=7
b=2
math.fmod(a,b)

1.0

## Константы
Посмотрите на результат и скажите, что за константы мы тут получили? Что вы про них знаете?

In [22]:
math.pi

3.141592653589793

In [23]:
math.e

2.718281828459045

## Возведение в степень, экспонента, логарифм.

### Возведение в степень: $с=a^b$

Попробуйте для разных чисел a и b.

Что если a=0, а если b = 0? Может ли а или b быть отрицательным? Нецелым?

Что мы получим если b=0.5? Как такую операцию назвать по-другому?

А если b=0.5 и a - отрицательное?


In [24]:
# Возведение в степень.
a=3
b=4
math.pow(a, b)

81.0


### Корень квадратный: $с=\sqrt{a}$

Функция `sqrt()`.

Попробуйте для разных чисел __a__

Что если __a=0__? Может ли __а__ быть отрицательным? Нецелым?

А как извлечь корень третьей степени?


In [25]:
# Корень квадратный.
a=16
math.sqrt(a)

4.0

In [26]:
# Корень кубический.
a=8
math.pow(a,1/3)

2.0

### Экспонента $с=e^b$
Очень часто в качестве основания __a__ используют экспоненту. Для этой операции сделали отдельную функцию.

Попробуйте сделать тоже самое с помощью `pow()`.

In [27]:
b=10
math.exp(b)

22026.465794806718

In [28]:
math.pow(math.e,b)

22026.465794806703

# Логарифм
# $ b=log_a(c) $

Если мы знаем результат возведения в степень __c__, знаем основание __a__, а хотим узнать, какая же степень __b__ должна при этом быть, то нам на помощь придет *логарифм*, функция `log()`.

Указываем сначала __c__ от которого мы ищем логарифм, а потом, необязательно, основание __a__ по которому мы ищем логарифм. Если основание не указано - используется *натуральный логарифм*.

Попробуйте с разными числами.

Может ли __с=0__? А меньше нуля может быть?

А если __c=1__, какой будет результат? Зависит ли он от __a__?

Может ли __a=0__ , __a=1__? А отрицательным __a__ может быть?  А дробным?





In [29]:
c=81
a=3
#math.log(x[, base])
math.log(c, a)

4.0

Наиболее часто используемые основания логарифмов сделаны в отдельных функциях, так быстрей и точней считать.

Двоичный логарифм, по основанию __a=2__: `log2`

Десятичный логарифм, по основанию __a=10__: `log10`

А как сделать *натуральный логарифм*? Какое у него основание?

In [30]:
с=4
math.log2(с)

2.0

In [31]:
с=100
math.log10(с)

2.0

In [32]:
с=math.e*math.e
math.log(с)

2.0

## Тригонометрические функции

- синус `sin`

- косинус `cos`

- тангенс `tan`

- арктангенс `atan` (обратная функция для тангенса) - часто используется в нейронных сетях.

- гиперболический тангенс `tanh` - тоже часто используется в нейронных сетях.

- и другие...

Для известных углов (например, 0, pi/4, pi/2 ,2 * pi и др.) посчитайте сами и сравните с расчетом в Питоне.

__Все углы указываются в радианах!__


In [33]:
x = math.pi/4 # зададим угол

In [34]:
math.cos(x)

0.7071067811865476

In [35]:
math.sin(x)



0.7071067811865476

In [36]:
#x = math.pi/2 #
math.tan(x) # а если x=math.pi/2?




0.9999999999999999

Арктангенс `atan(x)` - обратная функция для тангенса.

Позволяет узнать для какого угла тангенс равен x.

Поделим на Pi чтобы узнать этот угол.

Узнали?


In [37]:
# арктангенс - обратная функция для тангенса
x=1
math.atan(x)/math.pi

0.25

Гиперболический тангенс `tanh(x)` - довольно сложная функция, но по форме похожа на арктангенс.

> Формула для сведения, можете не запоминать сейчас:
> ![picture](https://drive.google.com/uc?id=1X1r5toeJ8xVW7aOvM18TL0OBVKHiT7ww)




In [ ]:
# гипертангенс
x=1000000000000
math.tanh(x)

1.0

## Факториал

Функция `factorial()`.

Находит факториал целого числа, произведение всех целых чисел начиная с единицы до заданного __a__.

Обозначается как "!"

Например 5! = 1 * 2 * 3 * 4 * 5 =120

Часто возникает в задачах с комбинациями различных событий.

Попробуйте для разных чисел __a__.

Может ли __a__ быть отрицательным? Дробным?

Чему равен факториал нуля?



In [ ]:
a=2
math.factorial(a)

2

## Домашнее задание
Изучите документацию на модуль `math`.

Посмотрите какие еще в нем есть функции.

Ответьте, как сконвертировать градусы в радианы и наоборот.
Сделайте это.


Что делать, если надо реализовать какую-то математическую функцию, которую вы не знаете, но она нужна? Внимательно читать документацию. Искать ответ в Интернет. Так часто поступают даже профессиональные разработчики  - нельзя все помнить и знать. Но нужно уметь __искать__ информацию.

Если какой-то функции нет в этом модуле - поищите в другом.

# 3. Модуль `numpy`

Библиотека `numpy` предназначена для работы с массивами. Для нас это самая любимая и часто используемая библиотека. Ее документацию можно посмотреть здесь: https://numpy.org/

Numpy создает и обрабатывает массивы как объекты своего собственного класса (типа): [`ndarray`](https://numpy.org/doc/1.18/reference/generated/numpy.ndarray.html#numpy.ndarray)

Основные его атрибуты это `shape` - форма массива и `dtype` - тип данных.  

Подключим библиотеку с помощью `import`и назовем коротко: `np`


In [38]:
import numpy as np

## Создание массивов

Для создания массивов используем функцию [`numpy.array()`](https://numpy.org/doc/1.18/reference/generated/numpy.array.html#numpy.array)

В ней мы указываем какой массив хотим создать.

Создадим массив, отобразим его и посмотрим, как называется его тип. Тип можно узнать с помощью команды `type()` .




In [39]:
a = np.array([1, 2, 3])

In [40]:
type(a)

numpy.ndarray

In [41]:
a.shape

(3,)

Видим, что тип - `numpy.ndarray` .

Это одномерный массив.

Теперь создадим двумерный массив (матрицу)

In [42]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])

In [43]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [44]:
b.shape

(2, 3)

Это двумерный массив. Атрибут `shape` показывает нам его форму, он имеет размер 2 на 3: 2 строки, 3 столбца.


Чтобы создавать массивы, заполненные какими-то числами, можно воспользоваться специальными функциями.

Например

`numpy.zeros(...)`  делает массив заданной формы, заполненный нулями
   
`numpy.ones(...)`  делает массив заданной формы, заполненный единицами

Мы указываем число элементов по каждой оси массива - разумеется это натуральные числа.

In [45]:
a=np.zeros((3, 5)) # двумерный массив из нулей, размером 3 на 5
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.ones((2, 3, 4)) # трехмерный массив из единиц размером 2 на 3 на 4

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Создадим любимую для линейной алгебры единичную матрицу с помощью команды `eye()`. Она квадратная, поэтому только один аргумент указываем - число строк. Если очень надо сделать по-другому, например не главную диагональ заполнить, то смотри документацию.   

In [47]:
np.eye(5) # создаем единичную матрицу

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Создать массив, но ничем его не заполнять можно с помощью функции `numpy.empty()`.

Заполнен он будет мусором, который остался в памяти, где создается такой массив.
Это гораздо быстрее, чем создать и заполнять массив нулями. Но нужно быть осторожным и потом все-таки заполнить массив, потому что мусор может быть любой.  

In [49]:
np.empty((3, 3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.42418987e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 0.00000000e+000]])

In [51]:
np.empty((3, 2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

Для создания последовательностей чисел, в NumPy имеется функция `numpy.arange(начало, конец, шаг)`, аналогичная встроенной в Python `range()`, только вместо списков она возвращает массивы, и принимает не только целые значения. Мы указываем __начало__ (необязательно, по умолчанию 0), __конец__ и __шаг__ (тоже не обязательно, по умолчанию 1) нашей последовательности. Конец не входит в последовательность. Шаг может быть отрицательным (но в этом случае конец должен быть меньше начала, иначе вернется пустой массив).

Попробуйте сами создать разные последовательности. Что получится если начало и конец совпадают?  А если шаг=0?

In [53]:

a=np.arange(20, 31, 5)
a

array([20, 25, 30])

In [57]:
a=np.arange(1, 0, -0.1)
a

array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1])

Вывести на экран массив можно командой `print()`.

In [59]:
a=np.arange(1,10.00001,0.001)
print(a)

[ 1.     1.001  1.002 ...  9.998  9.999 10.   ]


Видим, что выводится не весь массив. Это сделано для экономии места.

Если хотим задать сколько знаков после запятой выводить в числах, сколько чисел выводить на экран и др. надо задать опции вывода `set_printoptions`:

* параметр `treshold`: сколько чисел на экран выводить
* параметр `precision`: сколько знаков после запятой выводить в числах

Это влияет только на вывод, не на сами значения. Эти свойства будут применяться для всех выводов, не только для текущего, поэтому осторожно.


In [62]:
np.set_printoptions(threshold=10000, precision=3) # будем выводить до 10 десяти тысяч чисел, два знака после запятой.

In [63]:
print(a)

[ 1.     1.001  1.002  1.003  1.004  1.005  1.006  1.007  1.008  1.009
  1.01   1.011  1.012  1.013  1.014  1.015  1.016  1.017  1.018  1.019
  1.02   1.021  1.022  1.023  1.024  1.025  1.026  1.027  1.028  1.029
  1.03   1.031  1.032  1.033  1.034  1.035  1.036  1.037  1.038  1.039
  1.04   1.041  1.042  1.043  1.044  1.045  1.046  1.047  1.048  1.049
  1.05   1.051  1.052  1.053  1.054  1.055  1.056  1.057  1.058  1.059
  1.06   1.061  1.062  1.063  1.064  1.065  1.066  1.067  1.068  1.069
  1.07   1.071  1.072  1.073  1.074  1.075  1.076  1.077  1.078  1.079
  1.08   1.081  1.082  1.083  1.084  1.085  1.086  1.087  1.088  1.089
  1.09   1.091  1.092  1.093  1.094  1.095  1.096  1.097  1.098  1.099
  1.1    1.101  1.102  1.103  1.104  1.105  1.106  1.107  1.108  1.109
  1.11   1.111  1.112  1.113  1.114  1.115  1.116  1.117  1.118  1.119
  1.12   1.121  1.122  1.123  1.124  1.125  1.126  1.127  1.128  1.129
  1.13   1.131  1.132  1.133  1.134  1.135  1.136  1.137  1.138  1.139
  1.14

In [ ]:
np.set_printoptions(threshold=1000, precision=8) # вернем параметры по умолчанию
print(a)

[1.    1.001 1.002 ... 9.997 9.998 9.999]


## Базовые операции

Основные математические операции над массивами выполняются поэлементно. Создается новый массив, который заполняется результатами.

Для выполнения этих операций массивы должны быть одинаковой формы. Если будут разной -  получим ошибку.

In [64]:
a = np.array([20, 30, 40, 50]) # создадим один массив
a

array([20, 30, 40, 50])

In [65]:
b = np.arange(4) # создадим другой массив
b

array([0, 1, 2, 3])

In [66]:
с=a+b # сложим их
с

array([20, 31, 42, 53])

In [67]:
d=np.array([2,5])

In [68]:
a+d # размер не подходит для расширения

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [69]:
с=a - b # вычтем
с

array([20, 29, 38, 47])

In [70]:
с=a*b # умножим поэлементно
с

array([  0,  30,  80, 150])

In [71]:
с=a/b # поделим поэлементно
с

C:\Users\miphi\AppData\Local\Temp\ipykernel_9296\3468064263.py:1: RuntimeWarning: divide by zero encountered in divide
  с=a/b # поделим поэлементно


array([   inf, 30.   , 20.   , 16.667])

Ой-ой, что это, мы поделили на 0! Но NumPy справился с этим и вернул нам для такого случая специальное число - бесконечность `inf`. Бесконечности тоже числа, хоть и ненастоящие. Их можно складывать, вычитать,  умножать ...

Попробуйте сами и определите, что получается.

In [72]:
np.inf + np.inf

inf

In [73]:
-1*np.inf

-inf

In [74]:
np.inf * np.inf

inf

In [75]:
np.inf - np.inf

nan

При попытке вычесть одну бесконечность `inf` из другой мы тоже что-то получили.
А вы знаете сколько будет бесконечность минус бесконечность? А NumPy знает: будет `nan` - не число (not a number).

`nan` тоже ненастоящее число, и с ним можно делать математические операции.

Попробуйте сами и определите, что получается.

Все эти ненастоящие числа нужны чтобы облегчить программирование, но на самом деле они смысла не имеют, и если у вас такое число получилось - что-то не так. Поэтому иногда надо проверять результат, чтобы там не было бесконечностей или "нечисел".   

In [ ]:
np.nan*(-1)

nan

In [ ]:
np.nan+np.nan

nan

In [ ]:
np.nan+5

nan

In [76]:
a ** b # возведение в степень, первый аргумент - основание, второй - степень.

array([     1,     30,   1600, 125000])

In [ ]:
a % b  # Взятие остатка от деления (при взятии остатка от деления на 0 возвращается 0)

/tmp/ipython-input-2051496011.py:1: RuntimeWarning: divide by zero encountered in remainder
  a % b  # Взятие остатка от деления (при взятии остатка от деления на 0 возвращается 0)


array([0, 0, 0, 2])

Как мы уже отметили, формы массивов должны быть одинаковые (попробуйте что будет если нет).

Но есть исключение - когда один из аргументов - скаляр. Тогда он автоматически будет применяться к каждому элементу массива.

In [77]:
a + 1

array([21, 31, 41, 51])

In [78]:
1 + b

array([1, 2, 3, 4])

In [79]:
a ** 3

array([  8000,  27000,  64000, 125000])

In [80]:
2 ** b

array([1, 2, 4, 8])

In [81]:
a=np.ones((3,1))

In [82]:
b=2*np.transpose(a)

In [83]:
print(a.shape, b.shape)

(3, 1) (1, 3)


In [84]:
a*b # ?????

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [85]:
b*a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [86]:
a=3*np.ones((4,4))
b=-1*np.ones((4,1))
c=a+b
c

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

## Тригонометрия, округления
В `numpy` как и в `math` реализованы многочисленные тригонометрические операции.

Они работают с массивами поэлементно.

Округлений гораздо больше, самых разных типов:
`ceil()`, `floor()`, но и другие `round()` - округление до заданного числа знаков после запятой, `fix()` - округление до ближайшего целого со стороны нуля.

Поупражняйтесь с разными способами округления, сравните.


In [ ]:
np.cos(a) # косинус

array([[-0.9899925, -0.9899925, -0.9899925, -0.9899925],
       [-0.9899925, -0.9899925, -0.9899925, -0.9899925],
       [-0.9899925, -0.9899925, -0.9899925, -0.9899925],
       [-0.9899925, -0.9899925, -0.9899925, -0.9899925]])

In [ ]:
np.arctan(a) # арктангенс, название отличается от модуля math

array([[1.24904577, 1.24904577, 1.24904577, 1.24904577],
       [1.24904577, 1.24904577, 1.24904577, 1.24904577],
       [1.24904577, 1.24904577, 1.24904577, 1.24904577],
       [1.24904577, 1.24904577, 1.24904577, 1.24904577]])

In [ ]:
np.tanh(a) # гипертангенс

array([[0.99505475, 0.99505475, 0.99505475, 0.99505475],
       [0.99505475, 0.99505475, 0.99505475, 0.99505475],
       [0.99505475, 0.99505475, 0.99505475, 0.99505475],
       [0.99505475, 0.99505475, 0.99505475, 0.99505475]])

In [ ]:
c=5*np.cos(a) #
c

array([[-4.94996248, -4.94996248, -4.94996248, -4.94996248],
       [-4.94996248, -4.94996248, -4.94996248, -4.94996248],
       [-4.94996248, -4.94996248, -4.94996248, -4.94996248],
       [-4.94996248, -4.94996248, -4.94996248, -4.94996248]])

In [ ]:
np.round(c,2)

array([[-4.95, -4.95, -4.95, -4.95],
       [-4.95, -4.95, -4.95, -4.95],
       [-4.95, -4.95, -4.95, -4.95],
       [-4.95, -4.95, -4.95, -4.95]])

In [ ]:
np.ceil(c)

array([[-4., -4., -4., -4.],
       [-4., -4., -4., -4.],
       [-4., -4., -4., -4.],
       [-4., -4., -4., -4.]])

In [ ]:
np.fix(c)

array([[-4., -4., -4., -4.],
       [-4., -4., -4., -4.],
       [-4., -4., -4., -4.],
       [-4., -4., -4., -4.]])

## Агрегирующие функции.
Можно совместно обрабатывать все элементы массивов, а не каждый по отдельности. Такие функции называются агрегирующими.

In [89]:
a = np.array([[1, 2, 3], [4, 5, 6]]) # создадим массив
a

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
np.sum(a) # суммирование всех элементов массива между собой

np.int64(21)

или

In [88]:
a.sum() # другой способ вызова той же функции суммирования

np.float64(48.0)

In [91]:
a.min() # минимальный элемент массива

np.int64(1)

In [92]:
a.max() # максимальный элемент массива

np.int64(6)

По умолчанию, эти операции применяются к массиву, как если бы он был списком чисел, независимо от его формы. Однако, указав параметр `axis`, можно применить операцию для указанной оси (размерности) массива. Оси нумеруются начиная с 0 (первая ось имеет номер ноль).

In [93]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.min(axis=1) # минимум по строкам для каждого столбца

array([1, 4])

In [ ]:
a.min(axis=0) # минимум по столбцам для каждой строки

array([1, 2, 3])

Вообще, указание осей (особенно в случае тензоров - многомерных массивов) очень важно для таких функций. Мы будем часто пользоваться этим, когда будем изучать нейронные сети.

## Индексы, срезы, итерации

До сих пор мы обрабатывали все элементы массива, которые в нем есть. Но часто нужно работать только с некоторыми из них. Для этого надо узнать эти элементы. Например, хотим узнать какой в матрице первый элемент. Для этого нужно обратиться к этому элементу по его индексу (номеру).
В Python индексы начинаются с нуля, т.е. первый элемент имеет индекс 0.

Обращение к элементам, или как говорят *индексация*, массива выполняется с помощью квадратных скобок [] внутри которых мы указываем __срез__ тех индексов элементов, к которым хотим обратиться. Вспомним что такое __срез__ из уроков по основам Python. Это последовательность целых чисел, которую можно задать, например, использую оператор __начало:конец:шаг__


In [ ]:
a = np.arange(10) ** 3 # создадим массив. Какая у него форма?
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
a[4] # Посмотрим на первый элемент этого массива, помним что первый элемент имеет индекс 0.

np.int64(64)

In [ ]:
a[3:5] # Посмотрим сразу на четвертый и пятый элементы. Помним что в срезах конец не входит в диапазон, поэтому шестой элемент мы не получим

array([27, 64])

In [ ]:
a[[3,7]]


array([ 27, 343])

In [ ]:
a[[7,3]]

array([343,  27])

In [ ]:
a[[3,3]]

array([27, 27])

изменим четвертый и пятый элементы. Вообще, при изменении формы объектов слева и справа от знака присвоения = должны быть одинаковые. Но для скаляра это исключение.

In [ ]:
a[3:5] = 2 # изменяем
a

array([  0,   1,   8,   2,   2, 125, 216, 343, 512, 729])

А если вот так сделать, что получится?

In [ ]:
a[0.5] # такие индексы невозможны

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
a[::-1] # Что здесь происходит?

array([729, 512, 343, 216, 125,   2,   2,   8,   1,   0])

In [ ]:
a

array([  0,   1,   8,   2,   2, 125, 216, 343, 512, 729])

In [ ]:
a[-1]

np.int64(729)

In [ ]:
a[-100]

IndexError: index -100 is out of bounds for axis 0 with size 10

Вспомнив,  как создаются срезы, понимаем, что здесь __начало, конец__ опущены, а значит будут использованы значения по умолчанию, а __шаг = -1__. В результате получили массив, в котором элементы переставлены в обратном порядке.

У *многомерных* массивов на каждую ось приходится один индекс. Индексы передаются в виде последовательности чисел, разделенных запятыми (кортежами):

In [ ]:
b = np.array([[ 0,  1,  2,  3],
...           [10, 11, 12, 13],
...           [20, 21, 22, 23],
...           [30, 31, 32, 33],
...           [40, 41, 42, 43]]) # создадим двумерный массив
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [ ]:
b[2,3] # обратимся к элементу на третьей строке в четвертом столбце


np.int64(23)

тоже самое можно получить и так:

In [ ]:
b[(2,3)]

np.int64(23)

In [ ]:
b[[2,3]]

array([[20, 21, 22, 23],
       [30, 31, 32, 33]])

In [ ]:
b[[2,3],3]

array([23, 33])

In [ ]:
b[[2,3],[2,3]]

array([22, 33])

In [ ]:
b[2:3,2:3]

array([[22]])

In [ ]:
b[2:4,1:4]

array([[21, 22, 23],
       [31, 32, 33]])

или даже так

In [ ]:
b[2]

array([20, 21, 22, 23])

In [ ]:
b[2][3]

np.int64(23)

Но не следует путать

In [ ]:
b[:,2] # это третий столбец целиком (все строки)

array([ 2, 12, 22, 32, 42])

In [ ]:
b[:]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

и

In [ ]:
b[: 2] # это первая и вторая строки массива

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

Тут мы запятую не поставили, и NumPy считает, что мы указываем только один индекс, самый первый - индекс строк. А для столбцов индекс (по умолчанию) - все.

Теперь разгадайте вот такую индексацию:

In [ ]:
b[1:3, : : ] # что это за смайлик?

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

Мы указали *два* индекса, один для строк: `1:3`, т.е. вторая и третья строки,

другой для столбцов: ` : : ` здесь __начало, конец, шаг__ опущены и использованы значения по умолчанию. __начало = 0 , конец = "длина объекта" = 4 , шаг = 1__ т.е. первый, второй, третий и четвертый столбцы.

А что будет, если обратиться к элементу номер 100? Проверьте.

In [ ]:
b

In [ ]:
b[2:3][0] #????

array([20, 21, 22, 23])

In [ ]:
e=np.ones((2,3,4,2,3,4))

In [ ]:
e[...,2] # даже такое работает, опустили все предыдущие индексы

array([[[[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]]],



       [[[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1

Еще больше информации и примеров по индексации можно найти в [документации](https://numpy.org/devdocs/user/basics.indexing.html).

### Итерирование массивов
Зададим массив посложней. Узнаем его форму используя атрибут `shape`. Это трехмерный массив, 2 строки, 2 столбца, 3 третьих измерения (им не придумали названия).

In [ ]:
import numpy as np

In [ ]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))

In [ ]:
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [ ]:
a.shape

(2, 2, 3)

Итерирование многомерных массивов ведется по первой оси (т.е. строкам).

Изменяется номер строки, а все остальные индексы берутся "все".

В результате выполнится __две__ итерации (число строк равно двум).

Объект `row` будет массивом, который содержит:
* на первой итерации элементы из первой строки, всех столбцов и всех третьих измерений массива __a__.
* на второй итерации элементы из второй строки, всех столбцов и всех третьих измерений массива __a__.

In [ ]:
for row in a:
   print(row)
   print(' ')


[[ 0  1  2]
 [10 12 13]]
 
[[100 101 102]
 [110 112 113]]
 


Если нужно перебрать поэлементно весь массив, как если бы он был одномерным, для этого можно использовать `flat`. При этом наиболее быстро изменяется последний индекс, в нашем случае третий, потом второй (столбцы) и только в конце первый (строки).

Значит первая половина результата - это элементы с первой строки. Вторая половина - элементы со второй строки.

`flat` это итератор, он привязан к самому массиву, если изменим массив, то и его итератор поменяется, он _не_ делает копию массива. Если нужна копия объекта используйте `flatten` .

In [ ]:
a.flat

In [ ]:
for el in a.flat:
    print(el)


0
1
2
10
12
13
100
101
102
110
112
113


In [ ]:
a


array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])


Форма массива может быть изменена с помощью различных команд, результаты некоторых привязаны к самому массиву, изменив его изменится и результат, копии массива не создаются.

In [ ]:
a.ravel()  # Делает массив плоским, но сам массив не изменяется


array([  0,   1,   2,  10,  12,  13, 100, 101, 102, 110, 112, 113])

In [ ]:
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [ ]:
a.shape

(2, 2, 3)

In [ ]:
a.shape = (6, 2)  # Изменение формы, сам массив изменяется
a


array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

In [ ]:
a

array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

In [ ]:
b=a.transpose()  # Транспонирование, сам массив не изменяется
b

array([[  0,   2,  12, 100, 102, 112],
       [  1,  10,  13, 101, 110, 113]])

In [ ]:
a

array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

In [ ]:
a.reshape((3, 4))  # Изменение формы, но сам массив не изменяется

array([[  0,   1,   2,  10],
       [ 12,  13, 100, 101],
       [102, 110, 112, 113]])

In [ ]:
a

array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

### Объединение и разбиение массивов
Несколько массивов могут быть объединены вместе вдоль разных осей с помощью функций `hstack` и `vstack`.

`hstack()` — объединяет массивы по вторым осям (горизонтально),

`vstack()` — по первым (вертикально).

Есть функция `stack()` для объединения по любой оси и другие функции.

In [94]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [95]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

In [96]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [97]:
np.hstack((a, b))


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [98]:
np.column_stack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [99]:
np.row_stack((a, b))

C:\Users\miphi\AppData\Local\Temp\ipykernel_9296\2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Используя `hsplit()` можно разбить массив по горизонтальной (второй, столбцы) оси, указав либо число возвращаемых массивов одинаковой формы, либо номера столбцов, после которых массив разрезается "ножницами".

Аналогично `vsplit()` разрезает массивы по вертикальной (первой, строки) оси.

In [127]:
a = np.arange(12).reshape((2, 6))

In [128]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [129]:
z1,z2,z3=np.hsplit(a, 3)  # Разбить на 3 части по столбцам

In [130]:
z1, z2, z3

(array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]]))

In [134]:
np.hsplit(a, 2)  # Разрезать a после третьего и четвёртого столбца

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11]])]

In [132]:
np.vsplit(a, 2)  # Разбить на 2 части по строкам

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]

## Копии и представления

Простое присваивание __не создает__ копии массива:

In [112]:
a = np.arange(12)

In [113]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [114]:
b = a

In [115]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

__a__ и __b__ это два имени для одного и того же объекта ndarray, нового объекта не было создано.

Поменяв __a__, поменяется и __b__.

Чтобы проверить что это один и тот же объект можно использовать команду `is`

Она вернет *истину* (True) или *ложь* (False)

In [116]:
b is a # проверим что это один и тот же объект

True

In [117]:
b.shape

(12,)

In [118]:
b.shape = (3,4) # изменим массив b

In [119]:
a.shape # при этом изменился и массив а

(3, 4)

`view()` создаст __представление__ массива __a__.

Представление - это другой объект, он находится в другом месте памяти, но он связан с исходным массивом. Если поменяем массив __a__, то и его представление __c__ тоже поменяется.

Себе вы можете представить это так, мы смотрим на стол одним глазом и другим. Глаза разные, находятся в разных местах, но если стол поменяется, то обоими глазами мы увидим эти изменения.



In [120]:
c = a.view()

In [121]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
c is a

False

In [123]:
a[0,0]=100500 # изменим массив a
c # изменилось и его представление c

array([[100500,      1,      2,      3],
       [     4,      5,      6,      7],
       [     8,      9,     10,     11]])

In [ ]:
c[1,1]=-100500 # поменяем с
c # оно конечно изменилось

array([[ 100500,       1,       2,       3],
       [      4, -100500,       6,       7],
       [      8,       9,      10,      11]])

In [ ]:
a # и а тоже изменилось

array([[ 100500,       1,       2,       3],
       [      4, -100500,       6,       7],
       [      8,       9,      10,      11]])

Если нужно создать копию массива, которая будет независима от самого массива, но содержать те же данные, то используем `copy()`.


In [ ]:
d = a.copy()  # создается новый объект массива
d           # данные в нем такие же

array([[ 100500,       1,       2,       3],
       [      4, -100500,       6,       7],
       [      8,       9,      10,      11]])

In [ ]:
d is a # Это тот же объект? Нет

False

In [ ]:
a[0,0]=-1 # изменим массив a
a

array([[     -1,       1,       2,       3],
       [      4, -100500,       6,       7],
       [      8,       9,      10,      11]])

In [ ]:
d        # изменился ли массив d? Нет.

array([[ 100500,       1,       2,       3],
       [      4, -100500,       6,       7],
       [      8,       9,      10,      11]])

### Случайные числа в numpy

Очень часто для работы нужны *случайные* числа. Это числа, которые каждый раз принимают разные значения. Сегодня одно, завтра другое. На случайности построено много алгоритмов, а иногда качество такой случайности очень сильно влияет на работу.

В обычных компьютерах нет настоящих случайных чисел, это слишком дорого. Поэтому все пользуются __псевдослучайными__ числами, которые похожи на случайные, но на самом деле были один раз записаны и сохранены. В компьютерах есть большие таблицы псевдослучайных чисел, из которых они и выбираются (таблицы могут создаваться специальными алгоритмами-генераторами, см. например, [Вихрь Мерсена]( https://ru.wikipedia.org/wiki/Вихрь_Мерсенна) ).

Случайные числа описываются *распределением*, функцией, которая примерно показывает сколько разных случайных чисел каждого значения используется.

* Равномерное распределение (на отрезке [0 , 1]) означает что есть примерно одинаковое количество чисел каждого значения из этого отрезка. Например, 1000 штук со значением 0, 1005 штук со значением 0.1, 998 штук со значением 0.2 и т.д.

* Нормальное распределение  - если нарисовать функцию такого распределения, то она похожа на колокольчик, который расположен в нуле (точная формула нам сейчас не интересна). Это значит, что есть очень много чисел близких к нулю, но есть мало больших чисел, и чем больше число, тем меньше таких чисел в распределении.

Случайные числа из распределений выбираются наугад.

Для работы со случайными числами нам потребуются модули [`random`](https://pythonworld.ru/moduli/modul-random.html) и [`numpy.random`](https://pythonworld.ru/numpy/3.html).


In [124]:
import random

In [135]:
import numpy as np
import numpy.random as rand

Самый простой способ задать массив со случайными элементами - использовать функцию `sample()` (или `random()`, или `random_sample()`, или `ranf()` - это всё одна и та же функция). Ей мы сообщаем размеры массива, который хотим создать. Эта функция берет случайные числа из равномерного распределения на интервале [0, 1) (это значит, что ноль может выпасть, а единичка нет)

Позапускайте код ниже несколько раз, каждый раз будут другие числа возвращаться.

Если нужны случайные числа из другого диапазона, то их нужно сделать из этих. Сместить, растянуть диапазон.

In [138]:
np.random.sample() # одно случайное число

0.4231412167594075

In [142]:
a=-3
b=5
a+(b-a)*np.random.sample() # одно случайное число из диапазона [a,b)

-1.5222007246953533

In [143]:
np.random.sample(5) # Массив из 5 случайных чисел

array([0.71 , 0.87 , 0.081, 0.075, 0.599])

In [144]:
np.random.sample((1, 1, 4)) # 4 случайных числа в трехмерном массиве

array([[[0.18 , 0.619, 0.693, 0.617]]])

С помощью функции `randint()` или `random_integers()` можно создать массив из __целых__ случайных чисел.
Указываем аргументы: `low`, `high`, `size`: от какого `low`, до какого `high` числа (`randint` не включает в себя это число, а `random_integers` включает), и `size` - размеры массива.

In [145]:
np.random.randint(0, 3, 10)# массив из 10 случайных целых чисел от 0 до 2 (3 не включается)

array([1, 2, 0, 1, 2, 0, 2, 1, 1, 1], dtype=int32)

In [146]:
np.random.random_integers(0, 3, 10)# массив из 10 случайных целых чисел от 0 до 3 (3 включается)

C:\Users\miphi\AppData\Local\Temp\ipykernel_9296\1551969364.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 3 + 1) instead
  np.random.random_integers(0, 3, 10)# массив из 10 случайных целых чисел от 0 до 3 (3 включается)


array([3, 1, 3, 3, 3, 2, 1, 3, 2, 3], dtype=int32)

In [147]:
np.random.randint(0, 3, (2, 10))# двумерный массив случайных чисел от 0 до 2.

array([[1, 2, 0, 1, 0, 1, 1, 2, 0, 0],
       [2, 0, 0, 2, 0, 1, 1, 0, 1, 2]], dtype=int32)

Можно генерировать числа согласно различным распределениям (Гаусса, Парето и другие). Если понадобятся - см. документацию.

Чаще всего нужно равномерное распределение, которое можно получить с помощь функции `uniform()` , смысл аргументов такой же как у `random_integers`, начало и конец могут быть дробными.

In [148]:
np.random.uniform(2, 8, (2, 10)) # двумерный массив со случайными числами от 2 до 8

array([[6.685, 5.935, 7.688, 5.163, 6.5  , 3.239, 4.847, 7.85 , 6.94 ,
        6.769],
       [7.333, 4.68 , 2.502, 2.623, 4.041, 3.446, 4.518, 4.416, 5.324,
        2.013]])

Случайно перемешать массив можно с помощью функции `shuffle()`. Изменится сам массив.

In [149]:
a = np.arange(10)

In [150]:
a=np.random.randint(0,5,(2,3))

In [151]:
a

array([[3, 4, 2],
       [0, 2, 2]], dtype=int32)

In [155]:
np.random.shuffle(a)

In [156]:
a

array([[0, 2, 2],
       [3, 4, 2]], dtype=int32)

#### Инициализация генератора случайных чисел

Случайные числа берутся из таблицы случайных чисел, можно принудительно заставить компьютер брать случайные числа из одной и той же части таблицы, или из разных.

Первое может понадобиться, когда хотим, чтобы вычисления были одинаковыми.

Установить, с какого места таблицы начинать брать случайные числа можно с помощью `random.seed()`

Попробуйте сделать одинаковые и разные места и сравните результаты.

Увеличивайте число `seed` в 100 раз, пока не возникнет ошибка, так примерно узнаете какой размер таблицы.

In [159]:
np.random.seed(42) # начинаем с места №1000

np.random.random(10) # берем 10 случайных чисел

array([0.375, 0.951, 0.732, 0.599, 0.156, 0.156, 0.058, 0.866, 0.601,
       0.708])

In [160]:
np.random.seed(100) # Начинаем с другого места №100

np.random.random(10) # Берем 10 случайных чисел, они другие

array([0.543, 0.278, 0.425, 0.845, 0.005, 0.122, 0.671, 0.826, 0.137,
       0.575])

In [161]:
np.random.seed(1000) # Начинаем с того же места №1000

np.random.random(10) # Берем 10 случайных чисел, они такие же как в первом варианте

array([0.654, 0.115, 0.95 , 0.482, 0.872, 0.212, 0.041, 0.397, 0.233,
       0.842])

## Пример из будущих уроков
Мы будем часто выполнять операции с массивами, чтобы подготовить данные для наших расчетов.
Ниже кусок кода, который нам еще не раз встретится, который показывает как правильно формировать данные для расчетов.

Попробуйте по шагам объяснить, что тут происходит.

Не получится - не беда, узнаем позже.

In [162]:
batchsize, maps, h, w = 1, 1, 3, 3
data = (np.arange(batchsize * maps * h * w).reshape(batchsize, maps, h, w).astype(np.float32))

In [163]:
data

array([[[[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]]], dtype=float32)

In [164]:
import numpy as np

In [165]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
zeros = np.zeros(5)
ones = np.ones((2,3))
ar = np.arange(0, 10, 2)

zeros, ones, ar

(array([0., 0., 0., 0., 0.]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 2, 4, 6, 8]))

In [6]:
print("a:",a)
print("shape:",a.shape)
print("ndim:",a.ndim)
print("dtype:",a.dtype)

a: [1 2 3]
shape: (3,)
ndim: 1
dtype: int64


In [7]:
grades = np.array([6, 7, 8, 9, 10])

print("Оценки:",grades)
print("Средний балл:",grades.mean())

grades_min = grades.min()
grades_max = grades.max()
norm_grades = (grades - grades_min) / (grades_max - grades_min)

print("Нормализованные оценки:", norm_grades)

Оценки: [ 6  7  8  9 10]
Средний балл: 8.0
Нормализованные оценки: [0.   0.25 0.5  0.75 1.  ]
